using System.Collections.Generic;

namespace HyperSpace.UI;

/// <summary>
/// Declarative catalog of the sandbox panel controls.
/// Keeping labels and commands here leaves the panel focused on input, layout, and drawing.
/// </summary>
internal static class TransformationControlCatalog
{
    public static List<UiButton> CreateButtons() =>
    [
            new("TESSERACT", TransformationCommand.SelectTesseract),
            new("HYPERSPHERE", TransformationCommand.SelectHypersphere),
            new("4-SIMPLEX", TransformationCommand.SelectSimplex),
            new("IRREGULAR", TransformationCommand.SelectIrregular),
            new("4D SPIRAL", TransformationCommand.SelectSpiral),
            new("4D FRACTAL", TransformationCommand.SelectFractal),
            new("XY  +90", TransformationCommand.RotateXY),
            new("XZ  +90", TransformationCommand.RotateXZ),
            new("XW  +90", TransformationCommand.RotateXW),
            new("YZ  +90", TransformationCommand.RotateYZ),
            new("YW  +90", TransformationCommand.RotateYW),
            new("ZW  +90", TransformationCommand.RotateZW),
            new("SCALE +", TransformationCommand.ScaleUp),
            new("SCALE -", TransformationCommand.ScaleDown),
            new("+ X", TransformationCommand.MovePositiveX),
            new("- X", TransformationCommand.MoveNegativeX),
            new("+ Y", TransformationCommand.MovePositiveY),
            new("- Y", TransformationCommand.MoveNegativeY),
            new("+ Z", TransformationCommand.MovePositiveZ),
            new("- Z", TransformationCommand.MoveNegativeZ),
            new("+ W", TransformationCommand.MovePositiveW),
            new("- W", TransformationCommand.MoveNegativeW),
            new("RESET OBJECT", TransformationCommand.ResetObject),
            new("RESET CAMERA", TransformationCommand.ResetCamera),
            new("SHOW GRID", TransformationCommand.ToggleGrid),
            new("SHOW AXES", TransformationCommand.ToggleAxes),
            new("SHOW SURFACE", TransformationCommand.ToggleCells),
            new("SHOW EDGES", TransformationCommand.ToggleEdges),
            new("SHOW VERTICES", TransformationCommand.ToggleVertices),
            new("-", TransformationCommand.DecreaseSpiralR1),
            new("+", TransformationCommand.IncreaseSpiralR1),
            new("-", TransformationCommand.DecreaseSpiralR2),
            new("+", TransformationCommand.IncreaseSpiralR2),
            new("-", TransformationCommand.DecreaseSpiralK),
            new("+", TransformationCommand.IncreaseSpiralK),
            new("-", TransformationCommand.DecreaseSpiralSamples),
            new("+", TransformationCommand.IncreaseSpiralSamples),
            new("REGENERATE", TransformationCommand.RegenerateSpiral),
            new("PLAY CURVE", TransformationCommand.PlayCurve),
            new("RESET CURVE", TransformationCommand.ResetCurve),
            new("SHOW CURVE", TransformationCommand.ToggleCurve),
            new("SHOW POINTS", TransformationCommand.ToggleCurvePoints),
            new("SHOW DIRECTION", TransformationCommand.ToggleCurveDirection),
            new("-", TransformationCommand.DecreaseJuliaA),
            new("+", TransformationCommand.IncreaseJuliaA),
            new("-", TransformationCommand.DecreaseJuliaB),
            new("+", TransformationCommand.IncreaseJuliaB),
            new("-", TransformationCommand.DecreaseJuliaC),
            new("+", TransformationCommand.IncreaseJuliaC),
            new("-", TransformationCommand.DecreaseJuliaD),
            new("+", TransformationCommand.IncreaseJuliaD),
            new("-", TransformationCommand.DecreaseJuliaIterations),
            new("+", TransformationCommand.IncreaseJuliaIterations),
            new("-", TransformationCommand.DecreaseJuliaEscapeRadius),
            new("+", TransformationCommand.IncreaseJuliaEscapeRadius),
            new("-", TransformationCommand.DecreaseJuliaResolution),
            new("+", TransformationCommand.IncreaseJuliaResolution),
            new("PRESET 1", TransformationCommand.SelectJuliaPreset1),
            new("PRESET 2", TransformationCommand.SelectJuliaPreset2),
            new("PRESET 3", TransformationCommand.SelectJuliaPreset3),
            new("GENERATE", TransformationCommand.GenerateFractal),
            new("CANCEL", TransformationCommand.CancelFractalGeneration),
            new("RESET", TransformationCommand.ResetFractal),
            new("COLOR BY W", TransformationCommand.ColorFractalByW),
            new("COLOR BY ITER", TransformationCommand.ColorFractalByIterations),
            new("SHOW W SLICE", TransformationCommand.ToggleFractalWSlice),
            new("SLICE W -", TransformationCommand.DecreaseFractalSliceW),
            new("SLICE W +", TransformationCommand.IncreaseFractalSliceW),
            new("POINT 1", TransformationCommand.CycleFractalPointSize),
            new("PHYSICS", TransformationCommand.OpenPhysicsPanel),
            new("OBJECTS", TransformationCommand.ClosePhysicsPanel),
            new("PARTICLES", TransformationCommand.OpenParticlePhysicsView),
            new("GRAV LAB", TransformationCommand.OpenGravityLabView),
            new("N-BODY", TransformationCommand.OpenNBodyLabView),
            new("PHYSICS ON", TransformationCommand.TogglePhysicsEnabled),
            new("PLAY", TransformationCommand.PlayPhysics),
            new("PAUSE", TransformationCommand.PausePhysics),
            new("STEP", TransformationCommand.StepPhysics),
            new("TIME -", TransformationCommand.DecreaseTimeScale),
            new("TIME +", TransformationCommand.IncreaseTimeScale),
            new("-", TransformationCommand.DecreaseGravityX),
            new("+", TransformationCommand.IncreaseGravityX),
            new("-", TransformationCommand.DecreaseGravityY),
            new("+", TransformationCommand.IncreaseGravityY),
            new("-", TransformationCommand.DecreaseGravityZ),
            new("+", TransformationCommand.IncreaseGravityZ),
            new("-", TransformationCommand.DecreaseGravityW),
            new("+", TransformationCommand.IncreaseGravityW),
            new("ZERO G", TransformationCommand.SetZeroGravity),
            new("Y GRAVITY", TransformationCommand.SetYGravity),
            new("W GRAVITY", TransformationCommand.SetWGravity),
            new("Y + W GRAV", TransformationCommand.SetYWGravity),
            new("-", TransformationCommand.DecreaseInitialVelocityX),
            new("+", TransformationCommand.IncreaseInitialVelocityX),
            new("-", TransformationCommand.DecreaseInitialVelocityY),
            new("+", TransformationCommand.IncreaseInitialVelocityY),
            new("-", TransformationCommand.DecreaseInitialVelocityZ),
            new("+", TransformationCommand.IncreaseInitialVelocityZ),
            new("-", TransformationCommand.DecreaseInitialVelocityW),
            new("+", TransformationCommand.IncreaseInitialVelocityW),
            new("SPAWN 1", TransformationCommand.SpawnParticle),
            new("SPAWN 10", TransformationCommand.SpawnTenParticles),
            new("CLEAR", TransformationCommand.ClearParticles),
            new("COLLISIONS ON", TransformationCommand.TogglePhysicsCollisions),
            new("-", TransformationCommand.DecreaseRestitution),
            new("+", TransformationCommand.IncreaseRestitution),
            new("PLANE OFF", TransformationCommand.TogglePhysicsPlane),
            new("PAIR GRAV ON", TransformationCommand.ToggleMutualGravity),
            new("-", TransformationCommand.DecreaseGravitationalConstant),
            new("+", TransformationCommand.IncreaseGravitationalConstant),
            new("-", TransformationCommand.DecreaseGravitySoftening),
            new("+", TransformationCommand.IncreaseGravitySoftening),
            new("-", TransformationCommand.DecreaseCentralMass),
            new("+", TransformationCommand.IncreaseCentralMass),
            new("-", TransformationCommand.DecreaseOrbiterPositionX),
            new("+", TransformationCommand.IncreaseOrbiterPositionX),
            new("-", TransformationCommand.DecreaseOrbiterPositionY),
            new("+", TransformationCommand.IncreaseOrbiterPositionY),
            new("-", TransformationCommand.DecreaseOrbiterPositionZ),
            new("+", TransformationCommand.IncreaseOrbiterPositionZ),
            new("-", TransformationCommand.DecreaseOrbiterPositionW),
            new("+", TransformationCommand.IncreaseOrbiterPositionW),
            new("-", TransformationCommand.DecreaseOrbiterVelocityX),
            new("+", TransformationCommand.IncreaseOrbiterVelocityX),
            new("-", TransformationCommand.DecreaseOrbiterVelocityY),
            new("+", TransformationCommand.IncreaseOrbiterVelocityY),
            new("-", TransformationCommand.DecreaseOrbiterVelocityZ),
            new("+", TransformationCommand.IncreaseOrbiterVelocityZ),
            new("-", TransformationCommand.DecreaseOrbiterVelocityW),
            new("+", TransformationCommand.IncreaseOrbiterVelocityW),
            new("LOW", TransformationCommand.SelectLowOrbiterVelocity),
            new("MEDIUM", TransformationCommand.SelectMediumOrbiterVelocity),
            new("HIGH", TransformationCommand.SelectHighOrbiterVelocity),
            new("XY ONLY", TransformationCommand.SetOrbiterXYVelocity),
            new("XY + W", TransformationCommand.SetOrbiterXYWVelocity),
            new("TRAIL ON", TransformationCommand.ToggleGravityTrail),
            new("FIELD ON", TransformationCommand.ToggleGravityField),
            new("CLEAR TRAIL", TransformationCommand.ClearGravityTrail),
            new("-", TransformationCommand.DecreaseGravityTrailLength),
            new("+", TransformationCommand.IncreaseGravityTrailLength),
            new("RESET EXP", TransformationCommand.ResetGravityExperiment),
            new("APPLY", TransformationCommand.ApplyNBodyCount),
            new("APPLY", TransformationCommand.ApplyNBodySeed),
            new("RANDOM", TransformationCommand.RandomizeNBodySeed),
            new("GENERATE", TransformationCommand.GenerateNBodySystem),
            new("RESET", TransformationCommand.ResetNBodySystem),
            new("-", TransformationCommand.DecreaseNBodyRangeX),
            new("+", TransformationCommand.IncreaseNBodyRangeX),
            new("-", TransformationCommand.DecreaseNBodyRangeY),
            new("+", TransformationCommand.IncreaseNBodyRangeY),
            new("-", TransformationCommand.DecreaseNBodyRangeZ),
            new("+", TransformationCommand.IncreaseNBodyRangeZ),
            new("-", TransformationCommand.DecreaseNBodyRangeW),
            new("+", TransformationCommand.IncreaseNBodyRangeW),
            new("-", TransformationCommand.DecreaseNBodyMinimumSpeed),
            new("+", TransformationCommand.IncreaseNBodyMinimumSpeed),
            new("-", TransformationCommand.DecreaseNBodyMaximumSpeed),
            new("+", TransformationCommand.IncreaseNBodyMaximumSpeed),
            new("-", TransformationCommand.DecreaseNBodyMinimumMass),
            new("+", TransformationCommand.IncreaseNBodyMinimumMass),
            new("-", TransformationCommand.DecreaseNBodyMaximumMass),
            new("+", TransformationCommand.IncreaseNBodyMaximumMass),
            new("-", TransformationCommand.DecreaseNBodyRadiusScale),
            new("+", TransformationCommand.IncreaseNBodyRadiusScale),
            new("-", TransformationCommand.DecreaseNBodyPointScale),
            new("+", TransformationCommand.IncreaseNBodyPointScale),
            new("GRAVITY ON", TransformationCommand.ToggleNBodyGravity),
            new("MERGE ON", TransformationCommand.ToggleNBodyAggregation),
            new("EXACT", TransformationCommand.SelectNBodyExactGravity),
            new("MEAN FIELD", TransformationCommand.SelectNBodyApproximateGravity),
            new("COLOR W", TransformationCommand.ColorNBodyByW),
            new("COLOR MASS", TransformationCommand.ColorNBodyByMass),
            new("COLOR SPEED", TransformationCommand.ColorNBodyBySpeed),
            new("TRAIL OFF", TransformationCommand.DisableNBodyTrail),
            new("SELECTED", TransformationCommand.EnableSelectedNBodyTrail)

    ];
}
